// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, io;

  express = require('express');

  app = express.createServer(app);

  io = require('socket.io');

  io.listen(server);

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + '/views/index.html');
  });

  io.sockets.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'world'
    });
    socket.on('disconnect', function() {
      return socket.broadcast.emit('message', socket.pseudo + 'vient de se deconnecter');
    });
    socket.on('nouveauPseudo', function() {
      socket.pseudo = pseudo;
      console.log(socket.pseudo, "vient de se connecter");
      socket.broadcast.emit('nouveauPseudo', socket.pseudo);
      return socket.emit('pseudo', socket.pseudo);
    });
    return socket.on('message', function() {
      concole.log(soket.pseudo + ' ' + message);
      socket.broadcast.emit('message', socket.pseudo + ': ' + message);
      return socket.emit('message', socket.pseudo + ': ' + message);
    });
  });

  server.listen(8081);

}).call(this);
